### ISSUE TITLE
Bug: Delete enty in iteration (for/foreach) works incorrect on second and next deletions

### ISSUE THREAD

**Issue by MaxZhuravlev** [asimlqt/php-google-spreadsheet-client#124] opened 2016-03-08 19:38 UTC
Test:
Create such spreadsheet 
![image](https://cloud.githubusercontent.com/assets/1938294/13613204/38bb6d6e-e57c-11e5-86c2-2d527c6c8daa.png)

Run code that should delete rows with "Delete" text:
```php
        ...
        $entries=$listFeed->getEntries();
        foreach ($entries as $entry) {
            $values = $entry->getValues();
            if($values['numberordelete']=='Delete'){
                $entry->delete();
            }
        }
```

Result:
![image](https://cloud.githubusercontent.com/assets/1938294/13613278/783b7740-e57c-11e5-8fd3-f1bae32e4ffb.png)

First "delete me" row deleted correctly. Second and further deletions/editings are all displaced! Deleting wrong rows!

Also in same situations in long lists, if you try to delete last row, google will return error 400.

Workaround which works for me:

```php
        ...
        $entries=$listFeed->getEntries();
        $iReal=0;
        for($i=0;$i<count($entries);$i++){
            $entry=$entries[$i];
            $values = $entry->getValues();
            if($values['numberordelete']=='Delete'){
                $entries[$iReal]->delete(); $iReal--;
            }
            $iReal++;
        }
```
Result of testing this workaround on same spreadsheet:
![image](https://cloud.githubusercontent.com/assets/1938294/13613467/50f7a504-e57d-11e5-9cfd-682e4e5b35db.png)

**Comment by GustavoA23** [comment] 2016-03-10 14:45
Unfortunately this work around doesnt really apply to my situation. Even testing on a new blank sheet it returns a 400 error, and it seems to be related to the DefaultServiceRequest. 

```
PHP Fatal error:  Uncaught exception 'Google\Spreadsheet\Exception' with message 'Error in Google Request' in /var/www/html/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/DefaultServiceRequest.php:286
Stack trace:
#0 /var/www/html/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/DefaultServiceRequest.php(181): Google\Spreadsheet\DefaultServiceRequest->execute(Resource id #94)
#1 /var/www/html/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/ListFeed.php(89): Google\Spreadsheet\DefaultServiceRequest->post('https://spreads...', '<entry xmlns="h...')
#2 /var/www/html/textLoggerAlpha.php(257): Google\Spreadsheet\ListFeed->insert(Array)
#3 /var/www/html/textLoggerAlpha.php(164): batch(841, 1500)
#4 {main}
  thrown in /var/www/html/vendor/asimlqt/php-google-spreadsheet-client/src/Google/Spreadsheet/DefaultServiceRequest.php on line 286
```

**Comment by asimlqt** [comment] 2016-03-14 13:58
@MaxZhuravlev Thanks for raising this. I can confirm this is definitely a bug and is not to do with this library. It's a bug in the Spreadsheet API which Google need to fix. I have submitted a ticket so we'll just have to wait for their response.

https://code.google.com/a/google.com/p/apps-api-issues/issues/detail?id=4382

As temporary workaround in your situation you can just loop over the entries in reverse order:

`
foreach (array_reverse($worksheet->getListFeed()->getEntries()) as $entry) {
    $values = $entry->getValues();
    if ($values["numberordelete"] === "Delete") {
        $entry->delete();
    }
}
`

**Comment by DenoBY** [comment] 2016-05-03 07:36
@asimlqt Your code removes 1 - 3 entries and then issued an error 
`Uncaught PHP Exception Google\Spreadsheet\Exception\BadRequestException`

**Comment by asimlqt** [comment] 2016-05-03 21:00
@DenoBY Have you read the bug reported I posted for this issue? There's a link in my previous comment.

Apparently Google don't think this is a bug and are not going to fix it so 'm closing this issue.

**Closed by asimlqt** 2016-05-03 21:00 UTC

**Comment by DenoBY** [comment] 2016-05-03 21:18
@asimlqt Thank
